# Generated by Django 4.1.2 on 2022-10-19 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
